- hosts: localhost
  connection: local
  gather_facts: no           
  sudo: no
  vars:
    homebrew_taps:
      - homebrew/binary
      - homebrew/dupes
      - caskroom/cask
      - sanemat/font
    homebrew_packages:
      - { name: readline }
      - { name: openssl }
      - { name: openssl, state: linked, install_options: force }
      - { name: rbenv }
      - { name: ruby-build }
    homebrew_cask_packages:
      - { name: google-japanese-ime }
      - { name: alfred }
      - { name: night-owl }
      - { name: firefox }
      - { name: google-chrome }
      - { name: adobe-reader }
      - { name: macvim }
      - { name: java }
      - { name: skype }
      - { name: slack }
      - { name: sourcetree }
      - { name: karabiner }
      - { name: dash }
      - { name: atom }
      - { name: kobito }
      - { name: vagrant }
      - { name: virtualbox }

  tasks:
    # Homebrew
    - include: tasks/homebrew.yml

    # Homebrew Cask
    - include: tasks/homebrew-cask.yml

    # oh-my-zsh
    - include: tasks/zsh.yml

    # Ricty
    - include: tasks/ricty.yml

    # rbenv
    - include: tasks/rbenv.yml

  handlers:
    - name: run fc-cache
      shell: fc-cache -vf
