- hosts: localhost
  connection: local
  gather_facts: no           
  sudo: no
  vars:
    homebrew_taps:
      - homebrew/binary
      - homebrew/dupes
      - caskroom/cask
      - sanemat/font
    homebrew_packages:
      - { name: readline }
      - { name: openssl }
      - { name: openssl, state: linked, install_options: force }
      - { name: cscope }
      - { name: lua }
      - { name: wget }
      - { name: nmap }
      - { name: nodebrew }
      - { name: rbenv }
      - { name: ruby-build }
      - { name: trash }
      - { name: tmux }
      - { name: vim, install_options: with-lua }
      - { name: macvim, install_options: with-lua,with-cscope }
    homebrew_cask_packages:
      - { name: google-japanese-ime }
      - { name: xtrafinder }
      - { name: alfred }
      - { name: night-owl }
      - { name: firefox }
      - { name: google-chrome }
      - { name: adobe-reader }
      - { name: java }
      - { name: skype }
      - { name: slack }
      - { name: sourcetree }
      - { name: karabiner }
      - { name: dash }
      - { name: atom }
      - { name: kobito }
      - { name: vagrant }
      - { name: virtualbox }
    rubygems:
      - { name: pry }
      - { name: synx }
      - { name: cocoapods }
      - { name: tmuxinator }

  tasks:
    # Homebrew
    - include: tasks/homebrew.yml

    # Homebrew Cask
    - include: tasks/homebrew-cask.yml

    # oh-my-zsh
    - include: tasks/zsh.yml

    # Ricty
    - include: tasks/ricty.yml

    # rbenv
    - include: tasks/rbenv.yml

    # nodebrew
    - include: tasks/nodebrew.yml

    # vim
    - include: tasks/vim.yml

    # ruby gems
    - include: tasks/rubygems.yml

    # QuickLook
    - include: tasks/quicklook.yml

  handlers:
    - name: run fc-cache
      shell: fc-cache -vf
